language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email: false


before_install:
  - sudo apt-get update

install:
  - sudo apt-get install build-essential python-dev python-setuptools python-numpy python-scipy libatlas-dev libatlas3gf-base
  - sudo apt-get install libblas3gf libblas-doc libblas-dev liblapack3gf liblapack-doc liblapack-dev
  - pip install numpy
  - pip install scipy
  - pip install -U scikit-learn 
 
before_script:
  - make

script:
  - python setup.py develop
  - make vocabulary
  - make training
  - make evaluate

after_script:
  - make clean
